trinity/config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :users
  resources :bookings
  resources :houses
  get '/user_login' => 'sessions#new'
  post '/user_login' => 'sessions#create'
  delete '/user_login' => 'sessions#destroy'
end

trinity/app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :integer          not null, primary key
#  guests     :integer
#  created_at :datetime
#  updated_at :datetime
#  house_id   :integer
#  date_from  :date
#  date_to    :date
#  note       :text
#

class Booking < ActiveRecord::Base
  belongs_to :user
  has_many :houses
end

trinity/app/models/house.rb
# == Schema Information
#
# Table name: houses
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  image       :text
#  max_occ     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  index_image :text
#

class House < ActiveRecord::Base
  belongs_to :bookings
end

trinity/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  username        :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :bookings
end

trinity/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  private
  def authenticate_user
    if session[:user_id].present?
      @current_user = User.where(:id => session[:user_id]).first # Try to find a user but STAY CALM.
    end

    if @current_user.nil?
      session[:user_id] = nil
    end
  end
end

trinity/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find params[:id]
  end

  def new
    @booking = Booking.new
    @house = House.find params[:house_id]
  end

  def create
    @booking = Booking.create booking_params
    @house = ''
    if @booking.save
      request = PostageApp::Request.new(:send_message, {
  'headers'     => { 'from'     => @current_user.email,
                     'subject'  => 'Reservation Request' },
  'recipients'  => 'tmitche831@gmail.com',
  'content'     => {
    'text/plain'  => 'hey tom',
    'text/html'   => reservation_email(@booking, @house, @current_user)
  }
})
response = request.send
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find params[:id]
    @booking.update booking_params
    @user.save
  end

  def destroy
    @booking = Booking.find params[:id]
    @booking.destroy
    redirect_to booking_path
  end

  def reservation_email(booking, house, user)
    @booking, @house, @user = booking, house, user
    html = File.open("#{Rails.root}/app/views/bookings/reservation_email.html.erb").read
    template = ERB.new(html)
    template.result(binding)
  end

  private
  def booking_params
    params.require(:booking).permit(:guests, :house_id, :date_from, :date_to, :note)
  end
end

trinity/app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def create
    house = House.create house_params
    redirect_to house
  end

  def new
    @house = House.new
  end

  def edit
    @house = House.find params[:id]

  end

  def show
    @house = House.find params[:id]
  end

  def update
    house = House.find params[:id]
    house.update house_params
    redirect_to house
  end

  def destroy
    house = House.find params[:id]
    house.destroy
    redirect_to houses_path
  end

  private
  def house_params
    params.require(:house).permit(:id, :name, :description, :images, :occupied)
  end
end

trinity/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(:username => params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      # raise params.inspect
      redirect_to bookings_path
    else
      flash[:notice] = "Invalid login. Please try again."
      redirect_to user_login_path
    end
  end

    def destroy
      session[:user_id] = nil
      redirect_to bookings_path
    end
end

trinity/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_if_logged_in, :except => [:new, :create]
  # before_action :check_if_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :user_id, :first_name, :last_name, :email)
  end
end

trinity/app/helpers/application_helper.rb
module ApplicationHelper
  def smartnav
    links = ''
    if @current_user.try(:is_admin)
      links += "<li>" + link_to('View users', users_path) + "</li>"
    end

    if @current_user.present?
      links += "<li>"
      links += link_to('Logout ' + @current_user.username, user_login_path, :data => {:method => :delete, :confirm => 'Really logout?'})
      links += "</li>"
      links += "<li>"
      links += link_to('Edit ' + @current_user.username, edit_user_path(@current_user.id))
      links += "</li>"
    else
      links += "<p>"
      links += "To make a booking please " + link_to('Sign up', new_user_path ) + " or " + link_to('Sign in', user_login_path)
      links += "</p>"
    end

    links
  end
end

trinity/app/views/bookings/_form.html.erb
<div id="booking-form">
  <%= form_for @booking do |f| %>
    <h2><%= @house.name %></h2>
    <h3>Maximum Occupancy: <%= @house.max_occ %></h3>
    <h4>WARNING: All Booking requests are sent through email to the Owners.<br>Confirmation can take between 2-3days</h4>
      <p>
        <!-- Fix ME!!! -->
        <%#= f.hidden_field :house_id, @house.id %>
      </p>

      <p id="exp-guests">
        <%= f.label :guests, "Expected Guests: " %>
        <%= f.select :guests, 1..@house.max_occ %>
      </p>

      <p id="date-from">
        <%= f.label :date_from, "Date From: " %>
        <%= f.date_select :date_from, :order => [:day, :month, :year] %>
      </p>

      <p id="date-to">
        <%= f.label :date_to, "Date To: " %>
        <%= f.date_select :date_to, :order => [:day, :month, :year] %>
      </p>

      <p id="pers-note">
        <%= f.label :note, "Personal Note:" %>
        <br>
        <%= f.text_area :note, :placeholder => "Please include the House name and any other details you would like to enquire about", :rows => 10 %>
      </p>
      <%= f.button %>
  <% end %>

<iframe id="calendar-frame" src="https://www.google.com/calendar/embed?src=o2r9kpg0f5iru8saf6o05n9nt0%40group.calendar.google.com&ctz=Australia/Sydney" style="border: 0" width="500" height="300" frameborder="0" scrolling="no"></iframe>

</div>

trinity/app/views/bookings/index.html.erb
<div id="booking-index">
   <h1>Bookings</h1>
    <% if @current_user.present? %>
      <%= link_to('Make a new booking', houses_path) %>
      <br>

      </table>
    <% else %>
      <h3>Please Log in or Sign up to continue</h3>
    <% end %>
</div>

trinity/app/views/bookings/new.html.erb
<div id="booking-inputs">
<h1>New Booking</h1>
  <% if @current_user.present? %>
    <%= render :partial => 'form' %>
  <% end %>
</div>

trinity/app/views/bookings/reservation_email.html.erb
Username: <%= @user.username %>
<br>
Full Name: <%= @user.first_name + ' ' + @user.last_name %>
<br>
<!-- Fix MEEE!! -->
House: <%#= @house.name %>
<br>
Total Guests: <%= @booking.guests %>
<br>
Date From: <%= @booking.date_from %>
<br>
Date To: <%= @booking.date_to %>
<br>
<br>
Personal Note:<br>
<%= @booking.note %>

trinity/app/views/houses/index.html.erb
<div class="houses_contain">
<h1>Houses</h1>
<% @houses.each do |house| %>
  <div class="houses-div">
    <p id="house-name"><%= link_to(house.name, house) %></p>
    <p id="house-image"><%= image_tag(house.index_image, :class => 'display') %></p>
  </div>
<% end %>
</div>

trinity/app/views/houses/show.html.erb
<div class="house_show">
  <%= image_tag(@house.image, :class => 'thumb') %>
  <div id="house-info">
    <h2><%= @house.name %></h2>
    <p><%= @house.description %></p>
    <p>Maximum Occpunacy: <%= @house.max_occ %></p>
    <p><%= link_to('Book!', new_booking_path(:house_id => @house.id)) %></p>
    <!-- <p><%= link_to('Edit', edit_house_path(@house)) %></p>
    <p><%= link_to('Delete', @house, :method => :delete, :data => { :confirm => 'DONT DO IT!!'}) %></p> -->
  </div>
</div>

trinity/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trinity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main-container">
  <div id="name-box">
    <h1>Trinity Vineyard</h1>
    <nav id="main-links">
      <%= link_to('Home', users_path) %>
      <%= link_to('Houses', houses_path) %>
      <%= link_to('Bookings', bookings_path) %>
    </nav>
  </div>
  <div id="smartnav">
    <%== smartnav %>
  </div>
</div>



<%= yield %>

</body>
</html>

trinity/app/views/users/_form.html.erb
<div id="form_inputs">
  <%= form_for @user do |f| %>
    <h3>Username and Password</h3>
      <p>
        <%= f.label :username, "Username: " %>
        <%= f.text_field :username, :autofocus => true %>
      </p>

      <p>
        <%= f.label :password, "Password: " %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Confirm: " %>
        <%= f.password_field :password_confirmation %>
      </p>

      <hr>
    <h3>Other Information</h3>
      <p>
        <%= f.label :first_name, "First Name: " %>
        <%= f.text_field :first_name %>
      </p>

      <p>
        <%= f.label :last_name, "Last Name: " %>
        <%= f.text_field :last_name %>
      </p>

      <p>
        <%= f.label :email, "Email: " %>
        <%= f.text_field :email %>
      </p>
        <%= f.button %>
  <% end %>
</div>

trinity/app/views/users/edit.html.erb
<h2>Edit Info</h2>

<div id="inputs">
  <%= render :partial => 'form' %>
</div>

trinity/app/views/users/index.html.erb
<div id="logo_image">
  <h2>Home</h2>
  <img src="/assets/trinity_logo.png">
</div>

<div id="intro_container">
<h3>Introduction</h3>
<p>Trinity Vineyard is 60 acres of beautifully landscaped ground nestles in the centre of Lovedale.<br>Positioned next to Tatler Wines Vineyard and Winery... One of the hosts of The Lovedale Long Lunch.<br>Lovedale House and Trinity Cottage have fantastic views over a ten acre dam that is home to an amazing abundance of wildlife.<br>There are six acres of vines directly outside your door.<br><br>One of the most beautiful spots in the Hunter Valley<br>Peace and Serenity await</p>
</div>

trinity/app/views/users/new.html.erb
<h2>Sign up</h2>

<div id="user-inputs">
  <%= render :partial => 'form' %>
</div>